#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Mon Jan 19 20:41:31 GMT 2026
org.gradle.caching=true
systemProp.user.country=US
systemProp.user.language=en
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8 -Dsun.jnu.encoding\=UTF-8 -Duser.language\=en -Duser.country\=US
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
kapt.incremental.apt=true
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
kotlin.parallel.tasks.in.project=true
